name: Atualizar Painel Automático

on:
  schedule:
    - cron: '0 * * * *' # A cada 1 hora
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests speedtest-cli holidays

      - name: Run script
        run: python get_clima_agenda.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Atualização automática do painel" || echo "Sem mudanças"
          git push
